version: "3.7"
services:
  nc_mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - type: volume
        source: nc_mongo_data
        target: /data/db
  nc_news_backend:
    build: .
    depends_on:
      - nc_mongo
    ports:
      - "9090:9090"
    environment:
      - MONGODB_URI=mongodb://nc_mongo:27017/
volumes:
  nc_mongo_data: